packages:
  # 指定根目录直接子目录中的包
  # - 'my-app'
  # packages/ 直接子目录中的所有包
  - 'packages/*'
  # components/ 子目录中的所有包
  # - 'components/**'
  # 排除测试目录中的包
  # - '!**/test/**'
  # 定义目录和依赖版本号
catalog:
  vite: ^6.2.0
  typescript: ~5.7.2
  vue: ^3.5.13